language: objective-c
branches:
  only:
    - master
before_install:
    - brew update
    - brew uninstall xctool && brew install xctool
    - cd Tests && pod install && cd $TRAVIS_BUILD_DIR
script: rake test
